### ISSUE TITLE
Horizontally center Day name and Date with Notes fields

### ISSUE THREAD

**Issue by FifthRooter** [emilsbee/rainbow-tracker#16]
Would be great if those two texts could be aligned with the Notes fields instead of the Day's whole container, as it would look a lot more appealing like that.

Currently:
![image](https://user-images.githubusercontent.com/22204845/133832464-f579d36e-12b4-4349-b093-1640d9a1ce9a.png)

When centered would be:
![image](https://user-images.githubusercontent.com/22204845/133832502-3bf18c5a-5423-4cf2-a82b-9ec746eadba0.png)

**Comment by emilsbee** [comment]
Fixed!
