### ISSUE TITLE
Note doesn't center after stack increased above 1 line

### ISSUE THREAD

**Issue by FifthRooter** [emilsbee/rainbow-tracker#24]
![CleanShot 2021-10-11 at 09 23 23](https://user-images.githubusercontent.com/22204845/136749259-5cc8bcb3-4a24-4d32-8b0a-221bdeb15873.gif)

You can see that while the note is written in a single line, it's properly aligned and centered, but once you extend the stack, its formatting changes.

**Comment by emilsbee** [comment]
Solved to the point that the note in stack notes is at least horizontally centered.

**Comment by emilsbee** [comment]
Oh, that indeed solves the issue. Feel free to create a PR.
