### ISSUE TITLE
Analytics->Weekly section->Activities: unnamed activities are colored white and named "Empty"

### ISSUE THREAD

**Issue by FifthRooter** [emilsbee/rainbow-tracker#30]
Firstly, could the color of the unnamed activity be changed to the default color of the category, instead of white? I don't think it's necessary to have it be white, as it messes with the overall visual.

Second, could we perhaps agree with changing the name from "Empty" to something else, like "other"? Or perhaps name it after the category name, for example, "sleep" if the category name is "sleep", or "leisure" if the category name is "leisure"? I'd personally opt for the "other" name tho. Wdyt?

![image](https://user-images.githubusercontent.com/22204845/137988900-eae2c140-f744-47c5-98de-e94285dc4aff.png)

![image](https://user-images.githubusercontent.com/22204845/137988928-23d0fe99-a1d6-4b0f-8c24-961cace97426.png)

**Comment by emilsbee** [comment]
Yeah for sure I can change the color to the one that category has. I chose white initially to kind of indicate that they are "blank" so not yet colored (categorized). And regarding the name of the blank activity, I think let's go with "other" as that best describes what it actually is.

**Comment by emilsbee** [comment]
Fixed in commit https://github.com/emilsbee/rainbow-tracker/commit/e153a0d3563c866c190c0bb190f6f2fabec9284e.
