### ISSUE TITLE
Show also % of day spent on categories & activities

### ISSUE THREAD

**Issue by FifthRooter** [emilsbee/rainbow-tracker#32]
Right now analytics are only displaying the amount of hours spent on categories and activities, but it would also be great to display the time spent in % of the total time of a day/week/month/year.

![image](https://user-images.githubusercontent.com/22204845/138254595-17f12f7a-24bb-4aaa-b3ac-b3d66303ad8a.png)

**Comment by emilsbee** [comment]
Implemented!
